pool:
  vmImage: 'ubuntu-latest'

# Set variables
variables:
  clientDirectory: client
  serverDirectory: server
  stage: production
  serviceConnection: dukevotes
  appServiceName: dukevotes
  INLINE_RUNTIME_CHUNK: false
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
- script: 
    npm install
  displayName: 'npm install'
  workingDirectory: $(clientDirectory)

- script:
    npm install
  displayName: 'npm install server'
  workingDirectory: $(serverDirectory)
 
- script: 
    set "REACT_APP_STAGE=$(stage)" && npm run build
  displayName: 'npm build'
  workingDirectory: $(clientDirectory)
 
- task: AzureWebApp@1
  displayName: 'Deploy to App Service'
  inputs:
    azureSubscription: '$(serviceConnection)'
    appName: '$(appServiceName)'
    appType: 'webApp'
    package: '$(System.DefaultWorkingDirectory)'
    customWebConfig: '-Handler iisnode --NodeStartFile app.js --appType node'