# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Set variables
variables:
  clientDirectory: client
  serverDirectory: '$(System.DefaultWorkingDirectory)'
  stage: production
  serviceConnection: thebrotherhoodvotes
  appServiceName: thebrotherhoodvotes
  azureSubscription: thebrotherhoodvotes
  INLINE_RUNTIME_CHUNK: false
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
- script: 
    npm install
  displayName: 'npm install'
  workingDirectory: $(clientDirectory)

- script:
    npm install
  displayName: 'npm install server'
  workingDirectory: $(serverDirectory)
 
- script: 
    set "REACT_APP_STAGE=$(stage)" && npm run build
  displayName: 'npm build'
  workingDirectory: $(clientDirectory)
 
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: '$(clientDirectory)/build' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy server files'
  inputs:
    sourceFolder: '$(serverDirectory)' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: false
 
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
 
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'thebrotherhoodvotes'
    appType: 'webAppLinux'
    WebAppName: 'thebrotherhoodvotes'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'NODE|10-lts'
    StartupCommand: 'npm install'
